.gitignore
payments/forms.py
payments/templates/payments/confirm.html
payments/templates/payments/detail.html
payments/views.py
qiime_workshops/settings.py

Revised form flow using CBV FormMixin. Gets rid of the <td> label hack from this afternoon.

Reworking form flow

---

payments/middleware.py

Prod was bombing because of this import.

BUG: Fix debug toolbar in prod issue

---

README.md

- Fix travis badge
- Remove unneeded step from dev setup instructions

ENH: README tweaks

---

LICENSE

FIX: Transfer LICENSE ownership

---

payments/forms.py
payments/templatetags/form_errors.py
payments/views.py
templates/payments/_form_errors.html
templates/payments/order_detail.html
templates/payments/workshop_detail.html

Fixes #23.
Adds custom formset class for multi-form validation.
Also refactors form error template into templatetag.

ENH: Unique emails for all tickets on order

---

payments/models.py

BUG: Workshop get_absolute_url with subdomain

---

README.md
config/settings/base.py
config/settings/production.py

ENH: Add ADMINS setting, used for email error logs

---

payments/views.py

BUG: Stop flushing session

---

payments/views.py

ENH: Pass through additional info

---

.travis.yml
config/settings/test.py
requirements/test.txt

TST: Run migrations on travis

---

config/settings/base.py
config/urls/payments.py
payments/admin.py
payments/admin_filters.py
payments/models.py
requirements/base.txt
templates/admin/payments/order/change_form.html
templates/admin/payments/orderitem/change_form.html

ENH: Admin Filters

---

.travis.yml
config/settings/local.py
config/settings/production.py
config/settings/travis.py
manage.py

TST: Handle flake8 issues and remove the exclusions from testing

---

payments/admin.py
payments/admin_filters.py
payments/migrations/0023_order_refunded.py
payments/models.py
templates/admin/payments/order/change_form.html

- Ability to edit Order details from admin (Fixes #50)
- Add 'refunded' flag to Orders
- Update admin filters to handle refunds
- Add 'Export' to Order Items

ENH: Updates to Orders and Admin filters

---

templates/payments/base.html

MAINT: Only push Analytics on live site

---

README.md
payments/forms.py
payments/models.py

Previously it wouldn't validate until submitting, which was a pain to have to go through the entire process again.
Resolves #82 
Resolves #83

ENH: Add max value to registration form

---

payments/admin.py
payments/forms.py
payments/migrations/0029_posteroption.py
payments/models.py
payments/views.py
templates/payments/order_detail.html
templates/payments/workshop_confirm.html
templates/payments/workshop_detail.html

ENH: Adds support for workshop poster sessions

---

config/settings/base.py
config/settings/local.py
config/settings/production.py
config/urls/callback.py
payments/migrations/0030_workshop_email_description.py
payments/models.py
payments/views.py
requirements/base.txt
requirements/production.txt

ENH: Adds support for basic email receipts

---

payments/admin.py
payments/models.py
payments/tests/test_models.py

MAINT: Refactor Workshop.is_open

---

payments/views.py

Fixes #99 
Note, remember to update `ADMINS` environment variable when deploying to production.

ENH: BCC Admins on purchase confirmation email

---

config/settings/base.py
payments/middleware.py
payments/views.py
requirements/local.txt
templates/payments/workshop_list.html

MAINT: Verify cookies are enabled

---

payments/admin.py
payments/admin_filters.py
payments/models.py

- Fixed off-by-one rate error
- Fixed dupes in admin order-item filtering
- Added per-rate ticket counts workshop list on admin
- Added per-order ticket counts to order list on admin

ENH/BUG: Misc upgrades/fixes

---

payments/admin.py
payments/migrations/0031_workshop_dedicated_qiime2.py
payments/models.py

- "Dedicated QIIME 2" indicator
- Detailed ticket sales info in Admin
- Total price sold in Admin
Fixes #97

ENH: Admin overhauls

---

config/settings/base.py
config/settings/local.py
config/settings/production.py
payments/migrations/0001_initial.py
payments/migrations/0002_helptext.py
payments/migrations/0003_workshop_location.py
payments/migrations/0004_expand_email_scope.py
payments/migrations/0007_optionalworkshop_instructor.py
payments/migrations/0008_workshop_draft.py
payments/migrations/0009_workshopdraft_helptext.py
payments/migrations/0013_workshop_sales_open.py
payments/migrations/0014_option_workshop_url.py
payments/migrations/0015_order_datetime_change.py
payments/migrations/0017_billed_total_charfield.py
payments/migrations/0018_workshops_defaults.py
payments/migrations/0020_private_workshops.py
payments/migrations/0021_private_rates.py
payments/migrations/0022_increase_max_rate_price.py
payments/migrations/0023_order_refunded.py
payments/migrations/0029_posteroption.py
payments/migrations/0030_workshop_email_description.py
payments/migrations/0032_relabel_domain.py

proceed with caution: did not test

updates for flake8 compliance

---

LICENSE
workshops/payments/templates/payments/base.html

Update copyright header and `base.html` to reflect current year.

MAINT: Update copyright header and base.html to 2020
